version: "3.7"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: fileshare
      MYSQL_HOST: db
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_URL: "http://localhost:8080"
    volumes:
      - ./frontend/src:/app/src
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fileshare
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080